"""001_initial_schema

Revision ID: f08ddb315c7a
Revises: 
Create Date: 2026-09-16 15:32:18.874542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08ddb315c7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user'), 'audit_logs', ['user'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('OPERATING', 'ENGINEERING', 'TRD', 'S_AND_T', 'SAFETY', 'COMMERCIAL', 'IT_CRIS', name='departmentenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('trigger_source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_id'), 'optimization_runs', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_runs_run_id'), 'optimization_runs', ['run_id'], unique=True)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('CREW', 'MACHINE', 'EQUIPMENT', name='resourcetypeenum'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'BUSY', 'MAINTENANCE', 'UNAVAILABLE', name='resourcestatusenum'), nullable=False),
    sa.Column('current_location', sa.String(length=100), nullable=True),
    sa.Column('availability_window_start', sa.DateTime(), nullable=True),
    sa.Column('availability_window_end', sa.DateTime(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_resource_code'), 'resources', ['resource_code'], unique=True)
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('train_type', sa.Enum('PASSENGER', 'EXPRESS', 'FREIGHT', 'SPECIAL', name='traintypeenum'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.Column('destination', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_index(op.f('ix_trains_priority'), 'trains', ['priority'], unique=False)
    op.create_index(op.f('ix_trains_train_number'), 'trains', ['train_number'], unique=True)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('headquarters', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_code'), 'zones', ['code'], unique=True)
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_table('crews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('gang_code', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('supervisor_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crews_department_id'), 'crews', ['department_id'], unique=False)
    op.create_index(op.f('ix_crews_gang_code'), 'crews', ['gang_code'], unique=False)
    op.create_index(op.f('ix_crews_id'), 'crews', ['id'], unique=False)
    op.create_index(op.f('ix_crews_resource_id'), 'crews', ['resource_id'], unique=True)
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_code'), 'divisions', ['code'], unique=True)
    op.create_index(op.f('ix_divisions_id'), 'divisions', ['id'], unique=False)
    op.create_index(op.f('ix_divisions_zone_id'), 'divisions', ['zone_id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('machine_type', sa.String(length=50), nullable=False),
    sa.Column('home_shed', sa.String(length=50), nullable=True),
    sa.Column('max_output_per_hour', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_index(op.f('ix_machines_machine_type'), 'machines', ['machine_type'], unique=False)
    op.create_index(op.f('ix_machines_resource_id'), 'machines', ['resource_id'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('optimization_run_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('objective_score', sa.Float(), nullable=True),
    sa.Column('train_impact_score', sa.Float(), nullable=True),
    sa.Column('maintenance_coverage_percentage', sa.Float(), nullable=True),
    sa.Column('resource_utilization_percentage', sa.Float(), nullable=True),
    sa.Column('block_utilization_percentage', sa.Float(), nullable=True),
    sa.Column('feasibility_status', sa.String(length=20), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_optimization_run_id'), 'plans', ['optimization_run_id'], unique=False)
    op.create_index(op.f('ix_plans_plan_type'), 'plans', ['plan_type'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_index(op.f('ix_approvals_plan_id'), 'approvals', ['plan_id'], unique=False)
    op.create_table('corridors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('from_station', sa.String(length=50), nullable=True),
    sa.Column('to_station', sa.String(length=50), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('max_speed_kmph', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corridors_code'), 'corridors', ['code'], unique=True)
    op.create_index(op.f('ix_corridors_division_id'), 'corridors', ['division_id'], unique=False)
    op.create_index(op.f('ix_corridors_id'), 'corridors', ['id'], unique=False)
    op.create_table('block_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_code', sa.String(length=50), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=False),
    sa.Column('end_time', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('maintenance_allowed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='blockstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_windows_corridor_id'), 'block_windows', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_block_windows_id'), 'block_windows', ['id'], unique=False)
    op.create_index(op.f('ix_block_windows_window_code'), 'block_windows', ['window_code'], unique=True)
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_code'), 'stations', ['code'], unique=True)
    op.create_index(op.f('ix_stations_corridor_id'), 'stations', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.Column('asset_code', sa.String(length=50), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('line_number', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_corridor_id'), 'assets', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_station_id'), 'assets', ['station_id'], unique=False)
    op.create_table('rri_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_window_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.Column('conflicting_movement', sa.String(length=200), nullable=True),
    sa.Column('restriction_type', sa.String(length=100), nullable=False),
    sa.Column('active_time_window', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_window_id'], ['block_windows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rri_constraints_block_window_id'), 'rri_constraints', ['block_window_id'], unique=False)
    op.create_index(op.f('ix_rri_constraints_id'), 'rri_constraints', ['id'], unique=False)
    op.create_table('train_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_arrival', sa.String(length=20), nullable=True),
    sa.Column('scheduled_departure', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('line_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('block_window_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_window_id'], ['block_windows.id'], ),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_movements_block_window_id'), 'train_movements', ['block_window_id'], unique=False)
    op.create_index(op.f('ix_train_movements_corridor_id'), 'train_movements', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_train_movements_id'), 'train_movements', ['id'], unique=False)
    op.create_index(op.f('ix_train_movements_station_id'), 'train_movements', ['station_id'], unique=False)
    op.create_index(op.f('ix_train_movements_train_id'), 'train_movements', ['train_id'], unique=False)
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='criticalityenum'), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('safety_critical', sa.Boolean(), nullable=True),
    sa.Column('overdue', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('required_crew_count', sa.Integer(), nullable=True),
    sa.Column('required_machine_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'BLOCKED', name='taskstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_tasks_asset_id'), 'maintenance_tasks', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_department_id'), 'maintenance_tasks', ['department_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_id'), 'maintenance_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_task_id'), 'maintenance_tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_maintenance_tasks_task_type'), 'maintenance_tasks', ['task_type'], unique=False)
    op.create_table('block_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('requested_start', sa.DateTime(), nullable=True),
    sa.Column('requested_end', sa.DateTime(), nullable=True),
    sa.Column('requested_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=50), nullable=True),
    sa.Column('power_block_required', sa.Boolean(), nullable=True),
    sa.Column('signal_disconnection_required', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='blockstatusenum'), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_requests_department_id'), 'block_requests', ['department_id'], unique=False)
    op.create_index(op.f('ix_block_requests_id'), 'block_requests', ['id'], unique=False)
    op.create_index(op.f('ix_block_requests_request_id'), 'block_requests', ['request_id'], unique=True)
    op.create_index(op.f('ix_block_requests_task_id'), 'block_requests', ['task_id'], unique=False)
    op.create_table('plan_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_start', sa.String(length=30), nullable=True),
    sa.Column('scheduled_end', sa.String(length=30), nullable=True),
    sa.Column('assigned_corridor', sa.String(length=50), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('train_conflicts_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_tasks_id'), 'plan_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_plan_tasks_plan_id'), 'plan_tasks', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_tasks_task_id'), 'plan_tasks', ['task_id'], unique=False)
    op.create_table('power_block_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('affected_section', sa.String(length=100), nullable=False),
    sa.Column('affected_tracks', sa.String(length=100), nullable=True),
    sa.Column('isolation_required', sa.Boolean(), nullable=False),
    sa.Column('isolation_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('restoration_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('safety_requirement_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_power_block_requirements_id'), 'power_block_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_power_block_requirements_task_id'), 'power_block_requirements', ['task_id'], unique=True)
    op.create_table('replanning_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('affected_task_id', sa.Integer(), nullable=True),
    sa.Column('affected_train_id', sa.Integer(), nullable=True),
    sa.Column('affected_block_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('old_plan_id', sa.Integer(), nullable=True),
    sa.Column('new_optimization_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['affected_block_id'], ['block_windows.id'], ),
    sa.ForeignKeyConstraint(['affected_task_id'], ['maintenance_tasks.id'], ),
    sa.ForeignKeyConstraint(['affected_train_id'], ['trains.id'], ),
    sa.ForeignKeyConstraint(['new_optimization_run_id'], ['optimization_runs.id'], ),
    sa.ForeignKeyConstraint(['old_plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replanning_events_affected_block_id'), 'replanning_events', ['affected_block_id'], unique=False)
    op.create_index(op.f('ix_replanning_events_affected_task_id'), 'replanning_events', ['affected_task_id'], unique=False)
    op.create_index(op.f('ix_replanning_events_affected_train_id'), 'replanning_events', ['affected_train_id'], unique=False)
    op.create_index(op.f('ix_replanning_events_event_type'), 'replanning_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_replanning_events_id'), 'replanning_events', ['id'], unique=False)
    op.create_table('resource_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('assigned_start', sa.DateTime(), nullable=True),
    sa.Column('assigned_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'BUSY', 'MAINTENANCE', 'UNAVAILABLE', name='resourcestatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_allocations_id'), 'resource_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_resource_id'), 'resource_allocations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_allocations_task_id'), 'resource_allocations', ['task_id'], unique=False)
    op.create_table('safety_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('constraint_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('buffer_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('applicable_department', sa.String(length=50), nullable=True),
    sa.Column('applicable_location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_constraints_id'), 'safety_constraints', ['id'], unique=False)
    op.create_index(op.f('ix_safety_constraints_task_id'), 'safety_constraints', ['task_id'], unique=False)
    op.create_table('snt_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.String(length=100), nullable=False),
    sa.Column('affected_route', sa.String(length=100), nullable=True),
    sa.Column('disconnection_required', sa.Boolean(), nullable=False),
    sa.Column('disconnection_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('restoration_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('dependency_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snt_dependencies_id'), 'snt_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_snt_dependencies_task_id'), 'snt_dependencies', ['task_id'], unique=True)
    op.create_table('block_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_request_id', sa.Integer(), nullable=False),
    sa.Column('block_window_id', sa.Integer(), nullable=False),
    sa.Column('allocated_start', sa.DateTime(), nullable=True),
    sa.Column('allocated_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='blockstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_request_id'], ['block_requests.id'], ),
    sa.ForeignKeyConstraint(['block_window_id'], ['block_windows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_allocations_block_request_id'), 'block_allocations', ['block_request_id'], unique=False)
    op.create_index(op.f('ix_block_allocations_block_window_id'), 'block_allocations', ['block_window_id'], unique=False)
    op.create_index(op.f('ix_block_allocations_id'), 'block_allocations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_block_allocations_id'), table_name='block_allocations')
    op.drop_index(op.f('ix_block_allocations_block_window_id'), table_name='block_allocations')
    op.drop_index(op.f('ix_block_allocations_block_request_id'), table_name='block_allocations')
    op.drop_table('block_allocations')
    op.drop_index(op.f('ix_snt_dependencies_task_id'), table_name='snt_dependencies')
    op.drop_index(op.f('ix_snt_dependencies_id'), table_name='snt_dependencies')
    op.drop_table('snt_dependencies')
    op.drop_index(op.f('ix_safety_constraints_task_id'), table_name='safety_constraints')
    op.drop_index(op.f('ix_safety_constraints_id'), table_name='safety_constraints')
    op.drop_table('safety_constraints')
    op.drop_index(op.f('ix_resource_allocations_task_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_resource_id'), table_name='resource_allocations')
    op.drop_index(op.f('ix_resource_allocations_id'), table_name='resource_allocations')
    op.drop_table('resource_allocations')
    op.drop_index(op.f('ix_replanning_events_id'), table_name='replanning_events')
    op.drop_index(op.f('ix_replanning_events_event_type'), table_name='replanning_events')
    op.drop_index(op.f('ix_replanning_events_affected_train_id'), table_name='replanning_events')
    op.drop_index(op.f('ix_replanning_events_affected_task_id'), table_name='replanning_events')
    op.drop_index(op.f('ix_replanning_events_affected_block_id'), table_name='replanning_events')
    op.drop_table('replanning_events')
    op.drop_index(op.f('ix_power_block_requirements_task_id'), table_name='power_block_requirements')
    op.drop_index(op.f('ix_power_block_requirements_id'), table_name='power_block_requirements')
    op.drop_table('power_block_requirements')
    op.drop_index(op.f('ix_plan_tasks_task_id'), table_name='plan_tasks')
    op.drop_index(op.f('ix_plan_tasks_plan_id'), table_name='plan_tasks')
    op.drop_index(op.f('ix_plan_tasks_id'), table_name='plan_tasks')
    op.drop_table('plan_tasks')
    op.drop_index(op.f('ix_block_requests_task_id'), table_name='block_requests')
    op.drop_index(op.f('ix_block_requests_request_id'), table_name='block_requests')
    op.drop_index(op.f('ix_block_requests_id'), table_name='block_requests')
    op.drop_index(op.f('ix_block_requests_department_id'), table_name='block_requests')
    op.drop_table('block_requests')
    op.drop_index(op.f('ix_maintenance_tasks_task_type'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_task_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_department_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_asset_id'), table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_train_movements_train_id'), table_name='train_movements')
    op.drop_index(op.f('ix_train_movements_station_id'), table_name='train_movements')
    op.drop_index(op.f('ix_train_movements_id'), table_name='train_movements')
    op.drop_index(op.f('ix_train_movements_corridor_id'), table_name='train_movements')
    op.drop_index(op.f('ix_train_movements_block_window_id'), table_name='train_movements')
    op.drop_table('train_movements')
    op.drop_index(op.f('ix_rri_constraints_id'), table_name='rri_constraints')
    op.drop_index(op.f('ix_rri_constraints_block_window_id'), table_name='rri_constraints')
    op.drop_table('rri_constraints')
    op.drop_index(op.f('ix_assets_station_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_corridor_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_corridor_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_code'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_block_windows_window_code'), table_name='block_windows')
    op.drop_index(op.f('ix_block_windows_id'), table_name='block_windows')
    op.drop_index(op.f('ix_block_windows_corridor_id'), table_name='block_windows')
    op.drop_table('block_windows')
    op.drop_index(op.f('ix_corridors_id'), table_name='corridors')
    op.drop_index(op.f('ix_corridors_division_id'), table_name='corridors')
    op.drop_index(op.f('ix_corridors_code'), table_name='corridors')
    op.drop_table('corridors')
    op.drop_index(op.f('ix_approvals_plan_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_plans_plan_type'), table_name='plans')
    op.drop_index(op.f('ix_plans_optimization_run_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_machines_resource_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_machine_type'), table_name='machines')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_divisions_zone_id'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_id'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_code'), table_name='divisions')
    op.drop_table('divisions')
    op.drop_index(op.f('ix_crews_resource_id'), table_name='crews')
    op.drop_index(op.f('ix_crews_id'), table_name='crews')
    op.drop_index(op.f('ix_crews_gang_code'), table_name='crews')
    op.drop_index(op.f('ix_crews_department_id'), table_name='crews')
    op.drop_table('crews')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_code'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_trains_train_number'), table_name='trains')
    op.drop_index(op.f('ix_trains_priority'), table_name='trains')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_resources_resource_code'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_optimization_runs_run_id'), table_name='optimization_runs')
    op.drop_index(op.f('ix_optimization_runs_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_audit_logs_user'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
